settings:
  width: 800
  height: 600
  chat_height: 300
world:
  #  start_room: HALL
  start_room: RICK_SALOON
  player:
    start_pos: [400, 300]  # x, y
    animation:
      figure_img: "images/player_figure.png"
      chat_img: "images/player_figure.png"
      walking_sprites: "images/player_walking"
  officer:
      name: Officer Harper
      judge_path: "prompts/judge"
  rooms:
    RICK_SALOON:
      npcs:
      - name: Tim Kane
        start_pos: [200, 220]
        use_llm: true
        prompt: "prompts/tim.txt"
        chat_img: "images/tmp_tim_figure.png"
        figure_img: "images/tmp_tim_figure.png"
      - name: Bobby Herrerra
        start_pos: [540, 2180]
        use_llm: true
        prompt: "prompts/bobby.txt"
        chat_img: "images/bobby.png"
        figure_img: "images/bobby.png"
      - name: Fiona McAllister
        start_pos: [200, 400]
        use_llm: true
        prompt: "prompts/fiona.txt"
        chat_img: "images/fiona.png"
        figure_img: "images/fiona.png"
      - name: Harold Chun
        start_pos: [620, 500]
        use_llm: true
        prompt: "prompts/harold.txt"
        chat_img: "images/harold.png"
        figure_img: "images/harold.png"
      - name: Margeret Chun
        start_pos: [560, 480]
        use_llm: true
        prompt: "prompts/margaret.txt"
        chat_img: "images/margaret.png"
        figure_img: "images/margaret.png"
      - name: Louis Ferdinand Cagliostro
        start_pos: [620, 180]
        use_llm: true
        prompt: "prompts/louis.txt"
        chat_img: "images/louis.png"
        figure_img: "images/louis.png"
      - name: Pauline Thompson
        start_pos: [350, 470]
        use_llm: true
        prompt: "prompts/pauline.txt"
        chat_img: "images/pauline.png"
        figure_img: "images/pauline.png"
      items:
      - name: "Paper weight"
        description: "This is some text"
        pos: [200, 200]
        img_size: [50, 50]
        img: "images/items/marble_paperweight.png"
      doors:
      - out_room: RICK_HALL
        start_pos: [745, 190]
        polygon: [[-5, -25], [30, -40], [30, 20], [-5, 35]]

      - out_room: RICK_OVERVIEW
        start_pos: [420, 540]
        polygon: [[-82, 0], [80, 0], [77, 38], [-107, 38]]
      terrain: null
      background: "black"
      image: "images/rooms/ricks_saloon.png"

    RICK_HALL:
      npcs:
      - name: corpse
        start_pos: [400, 500]
      - name: Officer Harper
        start_pos: [580, 180]
        use_llm: true
        prompt: "prompts/officer.txt"
        chat_img: "images/officer.png"
        figure_img: "images/officer.png"
      doors:
      - out_room: RICK_SALOON
        start_pos: [135, 440]
        img: "images/door_closed.png"
      - out_room: RICK_BATHROOM
        start_pos: [745, 440]
      terrain: null
      background: "black"
      image: "images/rooms/rick_hallway.png"

    RICK_BATHROOM:
      npcs: []
      doors:
      - out_room: RICK_HALL
        start_pos: [135, 440]
        img: "images/door_closed.png"
      terrain: null
      background: "black"
      image: "images/rooms/rick_bathroom.png"

    RICK_OVERVIEW:
      npcs: []
      doors:
      - out_room: RICK_SALOON
        start_pos: [350, 300]
        img: "images/door_closed.png"
      - out_room: OFFICE_OVERVIEW
        start_pos: [700, 500]
        img: "images/door_closed.png"
      terrain: null
      background: "black"
      image: "images/rooms/rick_overview.png"

    OFFICE_OVERVIEW:
      npcs: []
      doors:
      - out_room: RICK_OVERVIEW
        start_pos: [100, 500]
        img: "images/door_closed.png"
      - out_room: OFFICE_HALL
        start_pos: [350, 300]
        img: "images/door_closed.png"
      terrain: null
      background: "black"
      image: "images/rooms/office_overview.png"

    OFFICE_HALL:
      npcs: []
      doors:
      - out_room: OFFICE_OVERVIEW
        start_pos: [350, 450]
        img: "images/door_closed.png"
      - out_room: OFFICE_PARTY
        start_pos: [150, 300]
        img: "images/door_closed.png"
      - out_room: OFFICE_RICKS_BUREAU
        start_pos: [450, 200]
        img: "images/door_closed.png"
      - out_room: OFFICE_BATHROOM
        start_pos: [500, 300]
        img: "images/door_closed.png"
      terrain: null
      background: "black"
      image: "images/rooms/office_hallway.png"

    OFFICE_PARTY:
      npcs: []
      doors:
      - out_room: OFFICE_HALL
        start_pos: [650, 450]
        img: "images/door_closed.png"
      terrain: null
      background: "black"
      image: "images/rooms/office_party.png"

    OFFICE_RICKS_BUREAU:
      npcs: []
      doors:
      - out_room: OFFICE_HALL
        start_pos: [450, 450]
        img: "images/door_closed.png"
      terrain: null
      background: "black"
      image: "images/rooms/office_ricks_bureau.png"

    OFFICE_BATHROOM:
      npcs: []
      doors:
      - out_room: OFFICE_HALL
        start_pos: [150, 250]
        img: "images/door_closed.png"
      terrain: null
      background: "black"
      image: "images/rooms/office_bathroom.png"
