settings:
  width: 800
  height: 650
  chat_height: 300
world:
  start_room: RICK_SALOON
  player:
    start_pos: [400, 450]  # x, y
    animation:
      figure_img: "images/player_figure.png"
      chat_img: "images/player_figure.png"
      walking_sprites: "images/player_walking"
  officer:
      name: Officer Harper
      judge_path: "prompts/judge"
  rooms:
    RICK_SALOON:
      pretty_name: Rick's Saloon
      npcs:
      - name: Tim Kane
        start_pos: [225, 220]
        use_llm: true
        prompt: "prompts/tim.txt"
        chat_img: "images/tmp_tim_figure.png"
        figure_img: "images/tmp_tim_figure.png"
      - name: Bobby Herrerra
        start_pos: [400, 310]
        use_llm: true
        prompt: "prompts/bobby.txt"
        chat_img: "images/bobby.png"
        figure_img: "images/bobby.png"
      - name: Fiona McAllister
        start_pos: [200, 400]
        use_llm: true
        prompt: "prompts/fiona.txt"
        chat_img: "images/fiona.png"
        figure_img: "images/fiona.png"
      - name: Harold Chun
        start_pos: [620, 350]
        use_llm: true
        prompt: "prompts/harold.txt"
        chat_img: "images/harold.png"
        figure_img: "images/harold.png"
      - name: Margeret Chun
        start_pos: [560, 480]
        use_llm: true
        prompt: "prompts/margaret.txt"
        chat_img: "images/margaret.png"
        figure_img: "images/margaret.png"
      - name: Louis Ferdinand Cagliostro
        start_pos: [620, 180]
        use_llm: true
        prompt: "prompts/louis.txt"
        chat_img: "images/louis.png"
        figure_img: "images/louis.png"
      - name: Pauline Thompson
        start_pos: [380, 170]
        use_llm: true
        prompt: "prompts/pauline.txt"
        chat_img: "images/pauline.png"
        figure_img: "images/pauline.png"
      doors:
      - out_room: RICK_HALL
        polygon: [[740, 165], [775, 150], [775, 210], [740, 225]]

      - out_room: RICK_OVERVIEW
        polygon: [[338, 540], [500, 540], [495, 578], [308, 578]]
      terrain: null
      background: "black"
      image: "images/rooms/ricks_saloon.png"

    RICK_HALL:
      pretty_name: Rick's Hallway
      npcs:
      - name: corpse
        start_pos: [400, 500]
      - name: Officer Harper
        start_pos: [580, 180]
        use_llm: true
        prompt: "prompts/officer.txt"
        chat_img: "images/officer.png"
        figure_img: "images/officer.png"
      doors:
      - out_room: RICK_SALOON
        polygon: [[113, 262], [113, 397], [46, 420], [47, 250]]
      - out_room: RICK_BATHROOM
        polygon: [[672, 267], [672, 400], [753, 426], [752, 255]]
      items:
      - name: "Dead body of Rick Martin"
        prompt: "prompts/Clue1.txt"
        pos: [500, 300]
        img_size: [75, 123]
        img: "images/items/victim_segmented.png"
      - name: "Paper weight"
        prompt: "prompts/Clue2.txt"
        pos: [350, 250]
        img_size: [25, 25]
        img: "images/items/marble_paperweight.png"
      - name: "Open fire door"
        prompt: "prompts/Clue4.txt"
        pos: [252, 80]
        img_size: [40, 30]
        img: "images/items/open_door.png"
      - name: "Note on the floor"
        prompt: "prompts/Clue3.txt"
        pos: [400, 350]
        img_size: [20, 20]
        img: "images/items/paper_note_segmented.png"
      terrain: null
      background: "black"
      image: "images/rooms/rick_hallway.png"

    RICK_BATHROOM:
      pretty_name: Rick's Bathroom
      npcs: []
      doors:
      - out_room: RICK_HALL
        polygon: [[110, 260], [110, 355], [47, 367], [47, 253]]
      terrain: null
      background: "black"
      image: "images/rooms/rick_bathroom.png"

    RICK_OVERVIEW:
      pretty_name: Rick's House
      npcs: []
      doors:
      - out_room: RICK_SALOON
        polygon: [[300, 296], [330, 296], [330, 288], [295, 288]]
      - out_room: OFFICE_OVERVIEW
        polygon: [[750, 420], [750, 515], [770, 515], [770, 420]]
      terrain: null
      background: "black"
      image: "images/rooms/rick_overview.png"

    OFFICE_OVERVIEW:
      pretty_name: The Office
      npcs: []
      doors:
      - out_room: RICK_OVERVIEW
        polygon: [[40, 400], [40, 490], [20, 490], [20, 400]]
      - out_room: OFFICE_HALL
        polygon: [[476, 297], [520, 297], [520, 303], [476, 303]]
      terrain: null
      background: "black"
      image: "images/rooms/office_overview.png"

    OFFICE_HALL:
      pretty_name: Office Entrance
      npcs: []
      doors:
      - out_room: OFFICE_OVERVIEW
        polygon: [[356, 520], [453, 520], [460, 570], [345, 570]]
      - out_room: OFFICE_PARTY
        polygon: [[28, 194], [28, 390], [80, 370], [80, 199]]
      - out_room: OFFICE_RICKS_BUREAU
        polygon: [[632, 55], [684, 55], [725, 25], [665, 25]]
      - out_room: OFFICE_BATHROOM
        polygon: [[729, 150], [729, 245], [776, 247], [775, 138]]
      terrain: null
      background: "black"
      image: "images/rooms/office_hallway.png"

    OFFICE_PARTY:
      pretty_name: Office Party
      npcs: []
      doors:
      - out_room: OFFICE_HALL
        polygon: [[749, 370], [749, 460], [780, 480], [780, 375]]
      terrain: null
      background: "black"
      image: "images/rooms/office_party.png"

    OFFICE_RICKS_BUREAU:
      pretty_name: Rick's and Tim's Office
      npcs: []
      doors:
      - out_room: OFFICE_HALL
        polygon: [[409, 509], [560, 509], [606, 565], [426, 565]]
      terrain: null
      background: "black"
      image: "images/rooms/office_ricks_bureau.png"

    OFFICE_BATHROOM:
      pretty_name: Office Bathroom
      npcs: []
      doors:
      - out_room: OFFICE_HALL
        polygon: [[54, 145], [52, 247], [136, 259], [138, 173]]
      terrain: null
      background: "black"
      image: "images/rooms/office_bathroom.png"
